/*
 View: contactInfo
WARNING! This file is generated by Slingr. You shouldn't add new functions or delete the functions
manually unless you know what you are doing. To be safe, only modify the scripts inside functions.
*/

function personalInfoTableRowsCalculation(record, options) {
    let columns = [
        {
            label: 'Attribute',
            name: 'attribute'
        },
        {
            label: 'Value',
            name: 'value'
        }
    ];
    let nationalityInfo = svc.http.get({url: 'https://api.nationalize.io/?name=' + record.field('fullName').val()});
    let nationality = nationalityInfo.country[0].country_id;
    let genderInfo = svc.http.get({url: 'https://api.genderize.io?name=' + record.field('fullName').val()});
    let gender = genderInfo.gender
    let ageInfo = svc.http.get({url: 'https://api.agify.io/?name=' + record.field('fullName').val()});
    let age = ageInfo.age;
    let rows = [
        {
            attribute: 'Nationality',
            value: nationality
        },
        {
            attribute: 'Gender',
            value: gender
        },
        {
            attribute: 'Age',
            value: age
        }
    ]
    return {
        columns: columns,
        rows: rows
    };
}

function notesTableRowsCalculation(record, options) {
    let rows = [];
    let filters = options.filters || {};
    let notes = record.field('notes').val();
    let from = options.from || 0;
    let to = options.to || notes.length;
    // apply filtering based on the 'note' column
    notes = notes.filter(function(noteItem) {
        let noteValue = noteItem.note
        if (filters.note && noteValue.toLowerCase().includes(filters.note.toLowerCase())) {
            return true;
        }
        return !filters.note;
    });
    // retrieve only the requested batch
    let notesBatch = notes.slice(from, to);
    notesBatch.forEach(function (noteItem) {
        rows.push({
            user: noteItem.user,
            note: noteItem.note
        });
    });
    let columns = [
        {
            name: 'user',
            label: 'User'
        },
        {
            name: 'note',
            label: 'Note',
            options: {
                allowFiltering: true
            }
        }
    ];
    return {
        columns: columns,
        rows: rows
    };
}
